version: '3.8'

services:
  app:
    build: .
    container_name: virtual-coach
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    devices:
      - "/dev/video0:/dev/video0"
